// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6_K2x5dvy3TTXSzlu1VOKve-i5xHThMk',
    appId: '1:476464166221:web:53e376ebd9c37352f83304',
    messagingSenderId: '476464166221',
    projectId: 'ggkk-73880',
    authDomain: 'ggkk-73880.firebaseapp.com',
    storageBucket: 'ggkk-73880.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeJAr1iVXSPaDEzRWA2dt0mpmygabfiQ8',
    appId: '1:476464166221:android:9cda9193f3e21c5ef83304',
    messagingSenderId: '476464166221',
    projectId: 'ggkk-73880',
    storageBucket: 'ggkk-73880.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoCw06nbL_d7kj7ZFBgnHPITTlShVfMOE',
    appId: '1:476464166221:ios:cfc17ab7f99f1ae8f83304',
    messagingSenderId: '476464166221',
    projectId: 'ggkk-73880',
    storageBucket: 'ggkk-73880.appspot.com',
    iosClientId: '476464166221-b9ujkaen52i4b4foqbgukt8o9plov3jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.gk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoCw06nbL_d7kj7ZFBgnHPITTlShVfMOE',
    appId: '1:476464166221:ios:c1c70e7051d351f8f83304',
    messagingSenderId: '476464166221',
    projectId: 'ggkk-73880',
    storageBucket: 'ggkk-73880.appspot.com',
    iosClientId: '476464166221-kv03okhacrnjbmqqekug9lgcl5d3fd0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.gk.RunnerTests',
  );
}
